from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()   #router 
router.register("list", views.DoctorViewset)   # amader view te 1 ta viewset eijnno 1 ta antena niyeci...
router.register("specialization", views.SpecializationViewset)   # amader view te 1 ta viewset eijnno 1 ta antena niyeci...
router.register("designation", views.DesignationViewset)   # amader view te 1 ta viewset eijnno 1 ta antena niyeci...
router.register("availabletime", views.AvailableTimeViewset)   # amader view te 1 ta viewset eijnno 1 ta antena niyeci...
router.register("review", views.ReviewViewset)   # amader view te 1 ta viewset eijnno 1 ta antena niyeci...
urlpatterns = [
    path("", include(router.urls)),
]